### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by olawanlejoel** [InventorsDev/inventors-frontend#4]
Please work on the Navbar of the project. Ensure you do the following:

- [ ] Navbar is responsive
- [ ] Dark mode styling works perfectly
- [ ] Implement logo for both modes

![Image](https://github.com/InventorsDev/inventors-frontend/assets/57611810/ac8c779c-a421-49c9-8a70-35efeb6a69fa)

**Comment by AsaoluElijah** [comment]
@olawanlejoel kindly review
